---
title: "generate_SI_figures"
author: "Sonia_Boscenco"
date: "2024-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
rm(list = ls())
gc()

setwd("~/Desktop/reznik/rrna-hotspots/analysis/")
```

```{r}
source("./prerequisites.R")

datadir          <- "~/Desktop/reznik/rrna-hotspots/data/processed/SI_figures/"
resultsdir       <- "~/Desktop/reznik/rrna-hotspots/figures/SI_figures/"

save             <- TRUE
```

# Extended Data 5a: mtDNA CN
```{r}
mtdnacn             <- read.csv(paste0(datadir, "mtdna_copy_number.csv"), header = TRUE, quote = "")
mtdnacn_long        <- pivot_longer(mtdnacn, cols = c(X1, X2, X3))
mtdnacn_mean        <- mtdnacn_long %>% 
                       group_by(Sample) %>% 
                       summarise(mean = mean(value))


mtdnacn_mean$Sample <- factor(mtdnacn_mean$Sample, levels = c("WT", "Low (9%)", "High (25%)"))
SI_mtdnacn          <- ggplot(mtdnacn_mean, aes(x = Sample, y = mean)) + 
                       geom_bar(stat = "identity", fill = "black", width = 0.8) + 
                       theme_std() + 
                       labs(y = "mtDNA copy no.", x = "Heteroplasmy") + 
                       scale_y_continuous(expand = c(0,0)) + 
                       scale_x_discrete(expand = c(0,0))

if(save == TRUE){ggsave(SI_mtdnacn, file = paste0(resultsdir, "SI_mtdnacn.pdf"), width = 1.5, height = 2)}
```

#Extended Data 5b: BE1 and BE2 Heteroplasmy Distribution
```{r}
het_df                    <- as.data.frame(rbind(fread("~/Desktop/reznik/1227_atac//data/het/BErep1-1227.csv") %>%
                             mutate(cell = gsub("-1", "-1", cell)) %>% mutate(lib = "BErep1"),
                             fread("~/Desktop/reznik/1227_atac//data/het/BErep2-1227.csv") %>%
                             mutate(cell = gsub("-1", "-2", cell)) %>% mutate(lib = "BErep2"),
                             fread("~/Desktop/reznik/1227_atac//data/het/WT-1227.csv") %>%
                             mutate(cell = gsub("-1", "-3", cell)) %>% mutate(lib = "WT")))

het_df9369             <- as.data.frame(rbind(fread("~/Desktop/reznik/1227_atac//data/het/BErep1-9369.csv") %>%
                                                mutate(cell = gsub("-1", "-1", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/BErep2-9369.csv") %>%
                                                mutate(cell = gsub("-1", "-2", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/WT-9369.csv") %>%
                                                mutate(cell = gsub("-1", "-3", cell)))
)

het_df1230             <- as.data.frame(rbind(fread("~/Desktop/reznik/1227_atac//data/het/BErep1-1230.csv") %>%
                                                mutate(cell = gsub("-1", "-1", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/BErep2-1230.csv") %>%
                                                mutate(cell = gsub("-1", "-2", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/WT-1230.csv") %>%
                                                mutate(cell = gsub("-1", "-3", cell)))
)

het_df1233             <- as.data.frame(rbind(fread("~/Desktop/reznik/1227_atac//data/het/BErep1-1233.csv") %>%
                                                mutate(cell = gsub("-1", "-1", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/BErep2-1233.csv") %>%
                                                mutate(cell = gsub("-1", "-2", cell)),
                                              fread("~/Desktop/reznik/1227_atac//data/het/WT-1233.csv") %>%
                                                mutate(cell = gsub("-1", "-3", cell)))
)


merged_het_df          <- merge(het_df, het_df9369, by = "cell")
merged_het_df          <- merge(merged_het_df, het_df1230, by = "cell")
merged_het_df          <- merge(merged_het_df, het_df1233, by = "cell")

het_df_lib1               <- merged_het_df[merged_het_df$lib == "BErep1", ]
het_df_lib1               <- het_df_lib1 %>% 
                             subset(cov1227 > 25 & cov1230 > 10 & cov1230 > 10 & cov9369 > 10 & af1230 < 0.05 & af1233 < 0.05 & af9369 < 0.05 & af1227 > 0.01)

het_df_lib1$af1227        <- as.numeric(het_df_lib1$af1227)

het_df_lib2               <- merged_het_df[merged_het_df$lib == "BErep2", ]
het_df_lib2               <- het_df_lib2 %>% 
                             subset(cov1227 > 25 & cov1230 > 10 & cov1230 > 10 & cov9369 > 10 & af1230 < 0.05 & af1233 < 0.05 & af9369 < 0.05 & af1227 > 0.01)
het_df_lib2$af1227        <- as.numeric(het_df_lib2$af1227)

hist_BE1_het              <- ggplot(het_df_lib1, aes(x = af1227)) + 
                             geom_histogram(bins = 50, linewidth = 0.1, fill = "black") + 
                             theme_classic(base_size = 7, 
                                           base_family = "ArialMT") + 
                             labs(x = "BE1 m.1227G>A heteroplasmy", y = "Frequency") + 
                             scale_y_continuous(expand = c(0,0)) + 
                             scale_x_continuous(expand = c(0,0))

hist_BE2_het              <- ggplot(het_df_lib2, aes(x = af1227)) + 
                             geom_histogram(bins = 50, linewidth = 0.01, fill = "black") + 
                             theme_classic(base_size = 7, 
                                           base_family = "ArialMT") + 
                             labs(x = "BE2 m.1227G>A heteroplasmy", y = "Frequency") + 
                             scale_y_continuous(expand = c(0,0)) + 
                             scale_x_continuous(expand = c(0,0))

if(save){ggsave(hist_BE1_het, file = paste0(resultsdir, "SI_BE1_het_histo.pdf"), width = 2.5, height = 1)}
if(save){ggsave(hist_BE2_het, file = paste0(resultsdir, "SI_BE2_het_histo.pdf"), width = 2.5, height = 1)}
```