---
title: "gel_all_figures_01_05"
author: "Sonia_Boscenco"
date: "1/5/2024"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
rm(list=ls())
setwd("~/Desktop/reznik/rrna-hotspots/analysis")
knitr::opts_chunk$set(echo = FALSE)
source('./prerequisites.R')

## sample sizes
n_samples_gel       <- 14079
n_samples_pcawg     <- 1951
n_samples_tcga      <- 10000

## load data
gel_hotspots        <- read.csv("../data/processed/fig1_2_tables/processed/fig1_2_tables/hotspots_snv_0223.txt", header = TRUE, sep = "\t") %>%
                       subset(q.value < 0.05)

setnames(gel_hotspots, "pos", "Start_Position")
setnames(gel_hotspots, "symbol", "Hugo_Symbol")

gel_hotspots$Start_Position <- as.integer(gel_hotspots$Start_Position)

gel_mutations       <- read.csv("../data/processed/fig1_2_tables/mtvariantcounts_0226.txt", sep = "\t", header = TRUE) 

# split the data frame to the ref and alt and remove all indels
split_columns       <- strsplit(gel_mutations$ShortVariantID, ":")
gel_mutations$Ref   <- sapply(split_columns, function(x) x[1])
gel_mutations$Pos   <- as.integer(sapply(split_columns, function(x) x[2]))
gel_mutations$Alt   <- sapply(split_columns, function(x) x[3])

indels              <- gel_mutations %>% 
                       subset(Ref == "-" | Alt == "-")

n_indels            <- length(unique(indels$Pos))
gel_mutations       <- gel_mutations %>% 
                       subset(!Ref == "-" & !Alt == "-")
n_snvs              <- length(unique(gel_mutations$Pos))
helix_muts          <- read.csv("../data/processed/fig1_2_tables/helix_mutations.csv", sep = ",", header = TRUE, row.names=1)  %>% 
                       subset(variant_type == "SNP") 

allpos              <- data.frame(1:16569)
colnames(allpos)    <- c('position')

annotations         <- read.csv("../data/processed/fig1_2_tables/mito_rRNA_annotations_NL.tsv", sep = "\t")

pcawg_mutations     <- read.csv("../data/processed/fig1_2_tables/data_mutations_pcawg.txt", sep = "\t", header = TRUE) %>% 
                       subset(Variant_Type == "SNP")
pcawg_hotspots      <- read.csv("../data/processed/fig1_2_tables/hotspots_snv_pcawg.txt", sep = "\t", header = TRUE) %>%
                       subset(q.value < 0.05)

tcga_mutations      <- read.csv("../data/processed/fig1_2_tables/data_mutations_tcga.txt", sep = "\t", header = TRUE) %>% 
                       subset(Variant_Type == "SNP")
tcga_hotspots       <- read.csv("../data/processed/fig1_2_tables/hotspots_snv_precalculated.txt", sep = "\t", header = TRUE) %>%
                       subset(q.value < 0.05)

pathogenic_pc       <- read.csv("../data/processed/fig1_2_tables/MitImpact_db_3.1.2.txt", sep = "\t", header = TRUE)

get_pdfs <- TRUE
```


# Figure 1

## 1b 
```{r panel_1b, fig.height = 2.5, fig.width = 5, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Lollipop plot of hotspot frequency 
# across the genome
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

panel_1b <- ggplot() +
  geom_segment(data = gel_hotspots, aes(x = Start_Position, xend = Start_Position, y = 0, yend = mutations_at_pos), color = "black") +
  geom_point(data = gel_hotspots, aes(x = Start_Position, y = mutations_at_pos, size = 2, alpha = 0.5)) + 
  scale_fill_identity() +
  theme_std() +
  scale_x_continuous(breaks = seq(min(gel_hotspots$Start_Position), max(filtered_gene_list$end), by = 1250), expand=(c(0,620))) +
  labs(x = "", 
       y = "# Mutations at Position") +
  theme(legend.position = "none") 
 
if(get_pdfs==T) ggsave('../figures/figure1/panel_1b.pdf',width=4,height=2.5)

```

## 1c

```{r panel_1c, fig.height = 2.5, fig.width = 2, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot of breakdown of hotspot by mtDNA classes
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gel_annotations        <- copy(gel_hotspots)
gel_annotations$class  <- ifelse(grepl("^MT-T", gel_annotations$Hugo_Symbol), "tRNA",
                                      ifelse(grepl("^MT-R", gel_annotations$Hugo_Symbol), "rRNA", "Protein Coding"))

n_genes_pc             <- length(unique(gel_annotations[gel_annotations$class == "Protein Coding", ]$Hugo_Symbol))
n_genes_rRNA           <- length(unique(gel_annotations[gel_annotations$class == "rRNA", ]$Hugo_Symbol))
n_genes_tRNA           <- length(unique(gel_annotations[gel_annotations$class == "tRNA", ]$Hugo_Symbol))

table_annotations      <- as.data.frame(table(gel_annotations$class))
table_annotations$prop <- table_annotations$Freq / sum(table_annotations$Freq)
table_annotations$Var1 <- factor(table_annotations$Var1, levels = c("rRNA","tRNA","Protein Coding"))

use_colors             <- c("#80B1D3","#D9D9D9","grey75")

panel_1c <- ggplot(table_annotations, aes(x = "", y = prop, fill = Var1)) + 
  geom_bar(position = "stack", stat = "identity") + 
  theme_std() +  
  scale_fill_manual(values = use_colors) + 
  labs(x = "", 
       y = 'Proportion of Hotspots', 
       fill = "") + 
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "left")

if(get_pdfs==T) ggsave('../figures/figure1/panel_1c.pdf',width=2,height=2.5)
```

## 1e

```{r panel_1e, fig.height = 2.5, fig.width = 2.5, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot of hotspots broken down by gene type
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gene_list_1e       <- copy(gene_list)
gene_list_1e$gene  <- paste0("MT-", gene_list_1e$gene)

table_pergene      <- as.data.frame(table(gel_hotspots$Hugo_Symbol))

# sort by frequency 
table_pergene      <- table_pergene %>% 
                      arrange(Freq)

table_pergene      <- merge(table_pergene, gene_list_1e, by.x = "Var1", by.y = "gene")
table_pergene$prop <- table_pergene$Freq / table_pergene$length

table_pergene       <- table_pergene %>% 
                       arrange(Freq)

table_pergene$Var1  <- factor(table_pergene$Var1, levels = table_pergene$Var1)
table_pergene$color <- ifelse(table_pergene$Var1 %in% c("MT-RNR1", "MT-RNR2"), "#80B1D3", "#D9D9D9")

panel_1e            <- ggplot(table_pergene, aes(x = Var1, y = Freq)) + 
                       geom_bar(stat = "identity", aes(fill = color)) + 
                       theme_std() + 
                       coord_flip() + 
                       scale_y_continuous(expand = c(0,0), position = "right")+ 
                       scale_fill_manual(values = c("#80B1D3", "#D9D9D9")) +
                       labs(x = "", 
                            y = "Number of Hotspots",
                            fill = "") +
                      theme(legend.box = element_blank(),
                            legend.text = element_blank(),
                            legend.key = element_blank(),
                            legend.position = "none")
  
if(get_pdfs==T) ggsave('../figures/figure1/panel_1e.pdf',width=2.5,height=2.5)
rm(gene_list_1e, table_pergene)
```

# Figure 2

## 2e

```{r panel_2e, fig.height = 2.5, fig.width = 2, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot comparing proportion rRNA annotations 
# of hotspots vs. non-hotspots
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rnr_muts_annotated             <- gel_mutations %>%
                                  subset(Gene %in% c("MT-RNR1", "MT-RNR2"))

rnr_muts_annotated$annotation  <- annotations$RNA_base_type[match(rnr_muts_annotated$Pos,annotations$POS)]
rnr_muts_annotated$is_hotspot  <- ifelse(rnr_muts_annotated$Pos %in% gel_hotspots$Start_Position,"Hotspot","Not Hotspot")

all_muts_melt                   <- melt((table(rnr_muts_annotated$annotation,rnr_muts_annotated$is_hotspot)))
colnames(all_muts_melt)         <- c("Annotation","Hotspot","Frequency")

all_muts_melt$Proportion        <- c(prop.table(all_muts_melt[all_muts_melt$Hotspot=="Hotspot",3]),prop.table(all_muts_melt[all_muts_melt$Hotspot=="Not Hotspot",3]))

use_cols                        <- c("#80b1d3", "#8dd3c7", "#fb8072")
panel_2e                        <- ggplot(all_muts_melt, aes(x=Hotspot, y=Proportion, fill=Annotation)) + 
                                   geom_bar(stat = "identity", position = "stack") + 
                                   theme_std() + 
                                   theme(legend.position = "left",
                                         axis.title.x = element_blank(),
                                         legend.title = element_blank()) +
                                   scale_fill_manual(values = use_cols)




p.value                          <- fisher.test(table(rnr_muts_annotated$annotation, rnr_muts_annotated$is_hotspot)) #0.0005267
p.value
if(get_pdfs==T) ggsave('../figures/figure2/panel_2e.pdf',width=2.5,height=2)

```
## 2f

```{r panel_2f, fig.height = 2, fig.width = 2, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Lollipop plot of hotspot mutation frequency RNR2 gene
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
## 2h

```{r panel_2h, fig.height = 2, fig.width = 2, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot comparing proportion of conserved (HOMOPLASMIC) vs. 
# non conserved positions in hotspots vs. not hotspots
# of rRNA genes
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rnr_positions                  <- data.frame(c(648:1601, 1671:3229))
colnames(rnr_positions)        <- c('position')

helix_collapsed                <- helix_muts %>%
                                  subset(gene %in% c("MT-RNR1", "MT-RNR2")) %>% 
                                  group_by(Start_Position) %>% 
                                  summarize(total_counts = sum(total_count), total_homs = sum(counts_hom), total_hets = sum(counts_het))

helixs_conserved               <- merge(rnr_positions, helix_collapsed,by.x='position',by.y='Start_Position',all.x = T)
helixs_conserved[(is.na(helixs_conserved))] <- 0

# subsetting for only RNR genes
rnr_hotpots                    <- gel_hotspots %>% 
                                  subset(Hugo_Symbol %in% c("MT-RNR1", "MT-RNR2"))

rnr_muts                       <- gel_mutations %>% 
                                  subset(Gene %in% c("MT-RNR1", "MT-RNR2"))

rnr_muts$Pos                   <- as.integer(rnr_muts$Pos)
rnr_hotpots$Start_Position     <- as.integer(rnr_hotpots$Start_Position)

# classify all mutations as hotpots or not
helixs_conserved$is_hotspot   <- ifelse(helixs_conserved$position %in% rnr_hotpots$Start_Position, "Hotspot", "Not Hotspot")

# can remove positions that have more than one mutation
rnr_muts                       <- rnr_muts %>%
                                  group_by(Pos) %>%
                                  distinct(Pos, .keep_all = TRUE)

helixs_conserved               <- merge(helixs_conserved ,rnr_muts, by.x='position', by.y='Pos', all.x = T)

helixs_conserved$is_conserved  <- ifelse(helixs_conserved$total_homs < 2, "Constrained", "Not Constrained")

table_of_constrained_hots      <- as.data.frame(table(helixs_conserved$is_conserved, helixs_conserved$is_hotspot))

n_hots                         <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Hotspot", ]$Freq)
n_not_hots                     <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Not Hotspot", ]$Freq)
table_of_constrained_hots$prop <- table_of_constrained_hots$Freq / c(n_hots, n_hots, n_not_hots,n_not_hots)
table_of_constrained_hots$Var1 <- factor(table_of_constrained_hots$Var1, levels = c("Not Constrained", "Constrained"))

use_cols                       <- c("#81b2d3", "#f47f73")

panel_2h                       <- ggplot(table_of_constrained_hots, aes(x = Var2, y = prop, fill = Var1)) + 
                                  geom_bar(stat = "identity") + 
                                  labs(x = "Hotspot",
                                       y = "Proportion",
                                       fill = "") + 
                                  scale_fill_manual(values = use_cols) +
                                  theme_std() + 
                                  theme(legend.position = "right",
                                        axis.title.x = element_blank())

p.value     <-  fisher.test(matrix(table_of_constrained_hots$Freq, ncol = 2)) #0.06988
p.value

p.value$est
if(get_pdfs==T) ggsave('../figures/figure2/panel_2h.pdf',width=2.5,height=2)
```
## 2i
```{r panel_2h, fig.height = 2, fig.width = 2, eval = TRUE}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot comparing proportion of conserved (HETEROPLASMIC) vs. 
# non conserved positions in hotspots vs. not hotspots
# of rRNA genes
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rnr_positions                  <- data.frame(c(648:1601, 1671:3229))
colnames(rnr_positions)        <- c('position')

helix_collapsed                <- helix_muts %>%
                                  subset(gene %in% c("MT-RNR1", "MT-RNR2")) %>% 
                                  group_by(Start_Position) %>% 
                                  summarize(total_counts = sum(total_count), total_homs = sum(counts_hom), total_hets = sum(counts_het))

helixs_conserved               <- merge(rnr_positions, helix_collapsed,by.x='position',by.y='Start_Position',all.x = T)
helixs_conserved[(is.na(helixs_conserved))] <- 0

# subsetting for only RNR genes
rnr_hotpots                    <- gel_hotspots %>% 
                                  subset(Hugo_Symbol %in% c("MT-RNR1", "MT-RNR2"))

rnr_muts                       <- gel_mutations %>% 
                                  subset(Gene %in% c("MT-RNR1", "MT-RNR2"))

rnr_muts$Pos                   <- as.integer(rnr_muts$Pos)
rnr_hotpots$Start_Position     <- as.integer(rnr_hotpots$Start_Position)

# classify all mutations as hotpots or not
helixs_conserved$is_hotspot   <- ifelse(helixs_conserved$position %in% rnr_hotpots$Start_Position, "Hotspot", "Not Hotspot")

# can remove positions that have more than one mutation
rnr_muts                       <- rnr_muts %>%
                                  group_by(Pos) %>%
                                  distinct(Pos, .keep_all = TRUE)

helixs_conserved               <- merge(helixs_conserved ,rnr_muts, by.x='position', by.y='Pos', all.x = T)

helixs_conserved$is_conserved  <- ifelse(helixs_conserved$total_hets < 1, "Constrained", "Not Constrained")

table_of_constrained_hots      <- as.data.frame(table(helixs_conserved$is_conserved, helixs_conserved$is_hotspot))

n_hots                         <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Hotspot", ]$Freq)
n_not_hots                     <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Not Hotspot", ]$Freq)
table_of_constrained_hots$prop <- table_of_constrained_hots$Freq / c(n_hots, n_hots, n_not_hots,n_not_hots)
table_of_constrained_hots$Var1 <- factor(table_of_constrained_hots$Var1, levels = c("Not Constrained", "Constrained"))

use_cols                       <- c("#81b2d3", "#f47f73")

panel_2h                       <- ggplot(table_of_constrained_hots, aes(x = Var2, y = prop, fill = Var1)) + 
                                  geom_bar(stat = "identity") + 
                                  labs(x = "Hotspot",
                                       y = "Proportion",
                                       fill = "") + 
                                  scale_fill_manual(values = use_cols) +
                                  theme_std() + 
                                  theme(legend.position = "right",
                                        axis.title.x = element_blank())

p.value     <-  fisher.test(matrix(table_of_constrained_hots$Freq, ncol = 2)) #0.007889
p.value
if(get_pdfs==T) ggsave('../figures/figure2/panel_2i.pdf',width=2.5,height=2)
```

# Supplementary Figures

## Supp2a: Mutation signatures (By Minsoo in GEL Server)

# Supplementary Figure 2a
```{r}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Comparing incidence of mutations in TCGA vs. GEL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Collapse gel mutations by positions 
gel_muts                 <- gel_mutations %>%
                            select(Pos, Freq) %>%
                            group_by(Pos) %>%
                            summarise(n = sum(Freq))

tcga_muts                <- as.data.frame(table(tcga_mutations$Start_Position))

# Annotate hotspots
gel_muts$is_hotspot      <- ifelse(gel_muts$Pos %in% gel_hotspots$Start_Position, TRUE, FALSE)
tcga_muts$is_hotspot     <- ifelse(tcga_muts$Var1 %in% tcga_hotspots$Start_Position, TRUE, FALSE)

# Merging
merged_tcga_gel         <- merge(gel_muts, tcga_muts, by.x = "Pos", by.y = "Var1", all = TRUE)
merged_tcga_gel[is.na(merged_tcga_gel)] <- 0

colnames(merged_tcga_gel)<- c("Start_Position", "GEL", "Hot_Gel", "TCGA", "Hot_TCGA")

merged_tcga_gel$col      <- ifelse(merged_tcga_gel$Hot_Gel == TRUE & merged_tcga_gel$Hot_TCGA == TRUE, "Hotspot GEL+TCGA",
                                    ifelse(merged_tcga_gel$Hot_Gel == FALSE & merged_tcga_gel$Hot_TCGA == TRUE, "Hotspot TCGA",
                                           ifelse(merged_tcga_gel$Hot_Gel == TRUE & merged_tcga_gel$Hot_TCGA == FALSE, "Hotspot GEL",  "Not Hotspot")))

# Ensure neither dots are behind the rest of the other dots
merged_tcga_gel          <- merged_tcga_gel[order(merged_tcga_gel$col != "Not Hotspot"), ]
color_order              <- c("Not Hotspot", "Hotspot GEL", "Hotspot TCGA", "Hotspot GEL+TCGA")
merged_tcga_gel$col      <- factor(merged_tcga_gel$col, levels = color_order)

supp2a                     <- ggplot(merged_tcga_gel, aes(x=GEL, y=TCGA, color=col)) + 
                              geom_point(alpha = 0.9) +
                              theme_classic() +
                              theme_std() + 
                              theme(legend.title = element_blank()) +
                                    xlab("# Samples Mutated in GEL") + 
                                    ylab("# Samples Mutated in TCGA") +
                              scale_color_manual(values = c("#FB8072", "#80B1D3","#B3DE69", "#D9D9D9"),
                                                 breaks = c("Hotspot GEL+TCGA", "Hotspot GEL", "Hotspot TCGA", "Not Hotspot"))

if(get_pdfs==T) ggsave('../figures/SI_figures/supp_2a.pdf',width=3.5,height=3)
```

# Supplementary Figure 2b
```{r}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Comparing incidence of mutations in PCAWG vs. GEL
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Collapse gel mutations by positions 
gel_muts                 <- gel_mutations %>%
                            select(Pos, Freq) %>%
                            group_by(Pos) %>%
                            summarise(n = sum(Freq))

pcawg_muts               <- as.data.frame(table(pcawg_mutations$Start_Position))

# Annotate hotspots
gel_muts$is_hotspot      <- ifelse(gel_muts$Pos %in% gel_hotspots$Start_Position, TRUE, FALSE)
pcawg_muts$is_hotspot    <- ifelse(pcawg_muts$Var1 %in% pcawg_hotspots$Start_Position, TRUE, FALSE)

# Merging
merged_pcawg_gel         <- merge(gel_muts, pcawg_muts, by.x = "Pos", by.y = "Var1", all = TRUE)
merged_pcawg_gel[is.na(merged_pcawg_gel)] <- 0

colnames(merged_pcawg_gel)<- c("Start_Position", "GEL", "Hot_Gel", "PCAWG", "Hot_PCAWG")

merged_pcawg_gel$col      <- ifelse(merged_pcawg_gel$Hot_Gel == TRUE & merged_pcawg_gel$Hot_PCAWG == TRUE, "Hotspot GEL+PCAWG",
                                    ifelse(merged_pcawg_gel$Hot_Gel == FALSE & merged_pcawg_gel$Hot_PCAWG == TRUE, "Hotspot PCAWG",
                                           ifelse(merged_pcawg_gel$Hot_Gel == TRUE & merged_pcawg_gel$Hot_PCAWG == FALSE, "Hotspot GEL",  "Not Hotspot")))

# Ensure neither dots are behind the rest of the other dots
merged_pcawg_gel          <- merged_pcawg_gel[order(merged_pcawg_gel$col != "Not Hotspot"), ]
color_order               <- c("Not Hotspot", "Hotspot GEL", "Hotspot PCAWG", "Hotspot GEL+PCAWG")
merged_pcawg_gel$col      <- factor(merged_pcawg_gel$col, levels = color_order)

supp2b                    <- ggplot(merged_pcawg_gel, aes(x=GEL, y=PCAWG, color=col)) + 
                             geom_point(alpha = 0.9) +
                             theme_classic() +
                             theme_std() + 
                             theme(legend.title = element_blank()) +
                                   xlab("# Samples Mutated in GEL") + 
                                   ylab("# Samples Mutated in PCAWG") +
                             scale_color_manual(values = c("#FB8072", "#80B1D3","#B3DE69", "#D9D9D9"),
                                                breaks = c("Hotspot GEL+PCAWG", "Hotspot GEL", "Hotspot PCAWG", "Not Hotspot"))

if(get_pdfs==T) ggsave('../figures/SI_figures/supp_2b.pdf',width=3.5,height=3)
```

## Supplementary Figure 3a
```{r supp_3a}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot of known disease causing variants
# in PC/rRNA/tRNA
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# load in known variants from mitomap
rnr_foswiki               <- read.csv("../data/processed/fig1_2_tables/MutationsRNACfrm  MITOMAP  Foswiki.csv", sep = ",", header = TRUE,   check.names = TRUE)  %>% 
                             select(Position, Locus)

pc_foswiki                <- read.csv("../data/processed/fig1_2_tables/ConfirmedMutations  MITOMAP  Foswiki.csv", sep = ",", header = TRUE, check.names = TRUE) %>% 
                             select(Position, Locus)

# merge pc and rrna
all_foswiki               <- rbind(rnr_foswiki, pc_foswiki)
all_foswiki               <- all_foswiki %>% 
                             distinct(Position, .keep_all = TRUE)

# label classification 
all_foswiki$Class         <- ifelse(grepl("MT-T", all_foswiki$Locus), "tRNA", 
                                    ifelse(grepl("MT-R", all_foswiki$Locus), "rRNA", "PC"))

# make frequency table
table_class_foswiki       <- as.data.frame(table(all_foswiki$Class))
table_class_foswiki$Var1  <- factor(table_class_foswiki$Var1, levels = c("rRNA", "PC", "tRNA"))

# save tableif needed
#write.csv(table_class_foswiki, file = "~/Desktop/reznik/gel_paper/tables/mitmomap_knownvars_table.csv")

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

barplot_mitomap_known_disease_causing <- ggplot(table_class_foswiki, aes(x = Var1, y = Freq)) + 
  geom_bar(stat = "identity", fill = "black") + 
  theme_classic(base_size = 7,
                base_family = "ArialMT") + 
  labs(x = "",
       y = "Number of Known Disease Causing Variants")

# save file
ggsave(barplot_mitomap_known_disease_causing, file = "../figures/SI_figures/supp_3a.pdf", width = 2, height = 2)

(which(pc_foswiki$Position %in% pc_hotspots$Start_Position))
# chisq. pvalue < 0.01 (3.5e-21 (tRNA vs rRNA), 4.7e-9(PC vs rRNA))

```

## Supplemental 2A/B
```{r}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot of conservation rate of the top 10
# hotspots in RNR1 and RNR2 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# conservation values from mitomap 
table_conservation <- data.frame(
  mutation = c(709, 879, 1227, 1552, 1169, 664, 1474, 1485, 1598, 1574),
  conservation = c(40, 95.56, 100, 91.11, 97.78, 91.11, 35.56, 100, 15.56, 91.11)
)
table_conservation$mutation <- factor(table_conservation$mutation, levels = rev(table_conservation$mutation))
conservation_figurernr1 <- ggplot(table_conservation, aes(x = mutation, y = conservation)) + 
  geom_bar(stat = "identity", fill = "black") + 
  theme_classic(base_family = "ArialMT", 
                base_size = 7) + 
  labs(x = "", 
       y = "Conservation Rate [%]") + 
  coord_flip() + 
  scale_y_continuous(expand = c(0,0), position = "right")

table_conservation <- data.frame(
  mutation = c(2702, 2492, 2571, 2573, 2333, 3010, 2916, 3022, 2690, 1888),
  conservation = c(75.56, 100, 100, 100, 95.56, 20, 95.56, 97.78, 100, 6.67)
)
table_conservation$mutation <- factor(table_conservation$mutation, levels = rev(table_conservation$mutation))
conservation_figurernr2 <- ggplot(table_conservation, aes(x = mutation, y = conservation)) + 
  geom_bar(stat = "identity", fill = "black") + 
  theme_classic(base_family = "ArialMT", 
                base_size = 7) + 
  labs(x = "", 
       y = "Conservation Rate [%]") + 
  coord_flip() + 
  scale_y_continuous(expand = c(0,0), position = "right")

```

```{r supp_1b}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot comparing proportion of conserved vs. 
# non conserved positions in hotspots vs. not hotspots
# in PC genes
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# get only protein coding genes
pc_genelist                    <- gene_list[!grepl("^R|^T|CR", gene_list$gene), ]

# create a list of all the positions in sequential order 
sequences_list                 <- apply(pc_genelist, 1, function(x) seq(from = x['start'], to = x['end']))
all_pos_pc                     <- unlist(sequences_list)
all_pos_pc_df                  <- data.frame(position = all_pos_pc)

# collapse helix with just cp

helix_pc                       <- helix_muts[!grepl("^MT-R|^MT-T|CR", helix_muts$gene), ]
helix_collapsed_pc             <- helix_pc %>%
                                  group_by(Start_Position) %>% 
                                  summarize(total_counts = sum(total_count), total_homs = sum(counts_hom), total_hets =                                       sum(counts_het))

helixs_conserved_pc            <- merge(all_pos_pc_df, helix_collapsed_pc,by.x='position',by.y='Start_Position',all.x = T)
helixs_conserved_pc[(is.na(helixs_conserved_pc))] <- 0

pc_hotspots                    <- gel_hotspots[!grepl("^MT-R|^MT-T|CR|ControlRegion|Translation_Start_Site", gel_hotspots$Hugo_Symbol), ]
pc_muts                        <- gel_mutations[!grepl("^MT-R|^MT-T|CR|ControlRegion|Translation_Start_Site", gel_mutations$Gene), ]
pc_muts                        <- pc_muts[!grepl("Translation_Start_Site", pc_muts$Class), ]

# classify all mutations as hotpots or not
helixs_conserved_pc$is_hotspot <- ifelse(helixs_conserved_pc$position %in% pc_hotspots$Start_Position, "Hotspot", "Not Hotspot")

# can remove positions that have more than one mutation
pc_muts                        <- pc_muts %>%
                                  group_by(Pos) %>%
                                  distinct(Pos, .keep_all = TRUE)

# merge germline conservation with all mutations 
helixs_conserved_pc             <- merge(helixs_conserved_pc ,pc_muts, by.x='position', by.y='Pos', all.x = T)
helixs_conserved_pc$is_conserved<- ifelse(helixs_conserved_pc$total_homs < 1, "Constrained", "Not Constrained")

table_of_constrained_hots      <- as.data.frame(table(helixs_conserved_pc$is_conserved, helixs_conserved_pc$is_hotspot))

n_hots                         <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Hotspot", ]$Freq)
n_not_hots                     <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Not Hotspot", ]$Freq)
table_of_constrained_hots$prop <- table_of_constrained_hots$Freq / c(n_hots, n_hots, n_not_hots,n_not_hots)
table_of_constrained_hots$Var1 <- factor(table_of_constrained_hots$Var1, levels = c("Not Constrained", "Constrained"))

use_cols                       <- c("#ccebc5", "#bebada")

panel_supp                     <- ggplot(table_of_constrained_hots, aes(x = Var2, y = prop, fill = Var1)) + 
                                  geom_bar(stat = "identity") + 
                                  labs(x = "Hotspot",
                                       y = "Proportion",
                                       fill = "") + 
                                  scale_fill_manual(values = use_cols) +
                                  theme_std() + 
                                  theme(legend.position = "right",
                                        axis.title.x = element_blank())

if(get_pdfs==T) ggsave('../figures_v2/panel_2j.pdf',width=2.5,height=2)
p.value     <-  fisher.test(matrix(table_of_constrained_hots$Freq, ncol = 2)) #0.09869
p.value
```

```{r supp_1b}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Barplot comparing proportion of conserved vs. 
# non conserved positions in hotspots vs. not hotspots
# in PC genes
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# get only protein coding genes
pc_genelist                    <- gene_list[!grepl("^R|^T|CR", gene_list$gene), ]

# create a list of all the positions in sequential order 
sequences_list                 <- apply(pc_genelist, 1, function(x) seq(from = x['start'], to = x['end']))
all_pos_pc                     <- unlist(sequences_list)
all_pos_pc_df                  <- data.frame(position = all_pos_pc)

# collapse helix with just cp

helix_pc                       <- helix_muts[!grepl("^MT-R|^MT-T|CR", helix_muts$gene), ]
helix_collapsed_pc             <- helix_pc %>%
                                  group_by(Start_Position) %>% 
                                  summarize(total_counts = sum(total_count), total_homs = sum(counts_hom), total_hets =                                       sum(counts_het))

helixs_conserved_pc            <- merge(all_pos_pc_df, helix_collapsed_pc,by.x='position',by.y='Start_Position',all.x = T)
helixs_conserved_pc[(is.na(helixs_conserved_pc))] <- 0

pc_hotspots                    <- gel_hotspots[!grepl("^MT-R|^MT-T|CR|ControlRegion|Translation_Start_Site", gel_hotspots$Hugo_Symbol), ]
pc_muts                        <- gel_mutations[!grepl("^MT-R|^MT-T|CR|ControlRegion|Translation_Start_Site", gel_mutations$Gene), ]
pc_muts                        <- pc_muts[!grepl("Translation_Start_Site", pc_muts$Class), ]

# classify all mutations as hotpots or not
helixs_conserved_pc$is_hotspot <- ifelse(helixs_conserved_pc$position %in% pc_hotspots$Start_Position, "Hotspot", "Not Hotspot")

# can remove positions that have more than one mutation
pc_muts                        <- pc_muts %>%
                                  group_by(Pos) %>%
                                  distinct(Pos, .keep_all = TRUE)

# merge germline conservation with all mutations 
helixs_conserved_pc             <- merge(helixs_conserved_pc ,pc_muts, by.x='position', by.y='Pos', all.x = T)
helixs_conserved_pc$is_conserved<- ifelse(helixs_conserved_pc$total_hets < 1, "Constrained", "Not Constrained")

table_of_constrained_hots      <- as.data.frame(table(helixs_conserved_pc$is_conserved, helixs_conserved_pc$is_hotspot))

n_hots                         <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Hotspot", ]$Freq)
n_not_hots                     <- sum(table_of_constrained_hots[table_of_constrained_hots$Var2 == "Not Hotspot", ]$Freq)
table_of_constrained_hots$prop <- table_of_constrained_hots$Freq / c(n_hots, n_hots, n_not_hots,n_not_hots)
table_of_constrained_hots$Var1 <- factor(table_of_constrained_hots$Var1, levels = c("Not Constrained", "Constrained"))

use_cols                       <- c("#ccebc5", "#bebada")

panel_supp                     <- ggplot(table_of_constrained_hots, aes(x = Var2, y = prop, fill = Var1)) + 
                                  geom_bar(stat = "identity") + 
                                  labs(x = "Hotspot",
                                       y = "Proportion",
                                       fill = "") + 
                                  scale_fill_manual(values = use_cols) +
                                  theme_std() + 
                                  theme(legend.position = "right",
                                        axis.title.x = element_blank())

if(get_pdfs==T) ggsave('../figures_v2/panel_2k.pdf',width=2.5,height=2)
p.value     <-  fisher.test(matrix(table_of_constrained_hots$Freq, ncol = 2)) #0.004554
p.value
```


```{r}
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Compare pathogenecity scores of PC hotspots to non
# hotspots 
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pc_muts$is_hotspot <- ifelse(pc_muts$Pos %in% pc_hotspots$Start_Position, "Hotspot", "Not Hotspot")

pc_pathogenics <- merge(pc_muts, pathogenic_pc, by.x = c("Pos", "Alt"), by.y = c("Start", "Alt"))

pc_pathogenics$APOGEE2 <- ifelse(pc_pathogenics$APOGEE2 %in% c("VUS+", "VUS-"), "VUS", pc_pathogenics$APOGEE2)
table_scores <- as.data.frame(table(pc_pathogenics$APOGEE2, pc_pathogenics$is_hotspot))

n_pc_muts <- sum(table_scores[table_scores$Var2 == "Not Hotspot",]$Freq)
n_pc_hots <- sum(table_scores[table_scores$Var2 == "Hotspot",]$Freq)

table_scores$n <- ifelse(table_scores$Var2 == "Hotspot", n_pc_hots, n_pc_muts)
table_scores$prop <- table_scores$Freq / table_scores$n

table_scores$Var1 <- factor(table_scores$Var1, levels = rev(c("VUS","Benign", "Likely-benign", "Likely-pathogenic", "Pathogenic")))

use_cols                       <- c("#bebada", "#8dd3c7", "#d9d9d9", "#d9d9d9", "#d9d9d9")
patho <- ggplot(table_scores, aes(x = Var2, y = prop, fill = Var1)) + 
  geom_bar(stat = "identity", size = 0.2, colour = "white") +  
  scale_fill_manual(values = use_cols) +
  theme_std() + 
  labs(x = "",
       y = "Proportion",
       fill = "APOGEE2 Classification")

if(get_pdfs==T) ggsave('../figures_v2/panel_2l.pdf',width=2.5,height=2)
p.value                          <- fisher.test(table(pc_pathogenics$APOGEE2, pc_pathogenics$is_hotspot)) #0.004478
```

# Positions that are germline conserved across the genome
```{r}

all_pos_df                  <- data.frame(Start_Position = allpos)
colnames(all_pos_df)        <- c("Start_Position")
helix_collapsed_all         <- helix_muts %>%
                                  group_by(Start_Position) %>% 
                                  summarize(total_counts = sum(total_count), total_homs = sum(counts_hom), total_hets =                                                     sum(counts_het))

all_pos_df                  <- merge(all_pos_df, helix_collapsed_all, by = "Start_Position", all.x = TRUE)
all_pos_df[is.na(all_pos_df)]<- 0 
all_pos_df$hetero_const     <- ifelse(all_pos_df$total_hets < 2, "Constrained", "Not Constrained")
all_pos_df$homos_const      <- ifelse(all_pos_df$total_homs < 2, "Constrained", "Not Constrained")
all_pos_df$special          <- ifelse(all_pos_df$total_homs < 2 & all_pos_df$total_hets >= 2, TRUE, FALSE)

special_positions           <- all_pos_df %>% subset(special == TRUE)
all_pos_df$hot              <- ifelse(all_pos_df$Start_Position %in% rnr_hotpots$Start_Position, TRUE, FALSE)

all_pos_df$class            <- ifelse(all_pos_df$homos_const == "Constrained" & all_pos_df$hetero_const == "Constrained", "Complete Constraint",
                                      ifelse(all_pos_df$homos_const == "Constrained" & all_pos_df$hetero_const == "Not Constrained", "Homoplasmic Only", 
                                             ifelse(all_pos_df$homos_const == "Not Constrained" & all_pos_df$hetero_const == "Not Constrained", "No Constrainst", "Heteroplasmic Only")))

table_constrainted          <- as.data.frame(table(all_pos_df$hot, all_pos_df$class))
table_constrainted$prop     <- ifelse(table_constrainted$Var1 == TRUE, table_constrainted$Freq / 31, table_constrainted$Freq / (16569-31))

ggplot(table_constrainted, aes(x = Var1, y = prop, fill = Var2)) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme_std() + 
  labs(x = "Hotspot", y = "Frcation of Genome", fill = "Constraint Type") + 
  scale_fill_brewer(palette = "Set3")

table_cons_het              <- as.data.frame(table(all_pos_df$hetero_const))
table_cons_hom              <- as.data.frame(table(all_pos_df$homos_const))
table_special               <- as.data.frame(table(all_pos_df$special))

table_cons_het$prop         <- table_cons_het$Freq / 16569
table_cons_hom$prop         <- table_cons_hom$Freq / 16569
table_special$prop          <- table_special$Freq / 16569

table_cons_het$x            <- c("Heteroplasmic")
table_cons_hom$x            <- c("Homoplasmic")
table_special$x             <- c("Heteroplasmic NO, Homoplasmic YES")

total_table_const           <- rbind(table_cons_het, table_cons_hom)
ggplot(table_special, aes(x = x, y = prop, fill = Var1)) + 
  geom_bar(stat = 'identity', position = 'stack') + 
  theme_std() + 
  labs(x = "", y = "Fraction of Genome", fill = "Heteroplasmic Not Constrained & Homoplasmic Constrained")

fig_intro <- ggplot(total_table_const, aes(x = x, y = prop, fill = factor(Var1, levels = c("Not Constrained", "Constrained")))) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme_std() + 
  theme_classic() +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) + 
  scale_fill_manual(values = c("#8dd3c7", "#bebada")) + 
  labs(x = "", y = "Fraction of Genome", fill = "")

ggsave("../figures_v2/constrained_number.pdf", width = 4.5, height = 2.5)
```
