---
title: "generate_functional_figures"
author: "Sonia_Boscenco"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Define paths
```{r}
data_dir             <- "~/Desktop/reznik/rrna-hotspots/data/processed/fig3_tables/functional/"
raw_data_dir         <- "~/Desktop/reznik/rrna-hotspots/data/raw/"
results_dir          <- "~/Desktop/reznik/rrna-hotspots/results/figures/"
save                 <- TRUE
```

# Read in all tables 
```{r}
gsea_proteomics           <- read.csv(paste0(data_dir, "GSEA_proteomics.csv"), header = TRUE, stringsAsFactors = FALSE)
colnames(gsea_proteomics) <- c("Pathway","High Heteroplasmy (33%)", "Low Heteroplasmy (10%)")

ocr                       <- read.csv(paste0(data_dir, "OCR.csv"), header = TRUE, stringsAsFactors = FALSE)
colnames(ocr)             <- c("WT", "High Heteroplasmy (40%)", "Low Heteroplasmy (24%)")

volcano_proteomics        <- read.csv(paste0(data_dir, "Proteomics.csv"), header = TRUE)
metabolomics              <- read.csv(paste0(raw_data_dir, "metabolomics_raw.csv"), header = TRUE)
```
## Fig 3h METABOLOMICS HEATMAP
```{r}
metabolomics_long         <- metabolomics %>% 
                             pivot_longer(cols = -Compound, names_to = "Condition", values_to = "Intensity") %>% 
                             group_by(Compound, Condition) %>% 
                             mutate(Replicate = row_number(), .keep = "all") %>% 
                             mutate(Sample = paste0(Condition, "_", Replicate)) 

total_intensity            <- metabolomics_long %>%
                              group_by(Sample) %>% 
                              summarise(Total = sum(Intensity))

tpm                        <- metabolomics_long %>%
                              left_join(total_intensity, by = "Sample") %>% 
                              mutate(Relative_Abundance = Intensity / Total, 
                                     TPM = Relative_Abundance*1e6) 

averaged_metabo            <- tpm %>%
                              group_by(Condition, Compound) %>% 
                              summarise(Average = exp(mean(log(TPM))), .groups = "drop") 

averaged_metabo_wide       <- pivot_wider(averaged_metabo, id_cols = c("Compound"), names_from = "Condition", values_from = "Average")
averaged_metabo_wide$`High Heteroplasmy (25%) vs WT` <- averaged_metabo_wide$LLT2/averaged_metabo_wide$CT2
averaged_metabo_wide$`Low Heteroplasmy (9%) vs WT` <- averaged_metabo_wide$HLT2/averaged_metabo_wide$CT2
averaged_metabo_wide$`High Heteroplasmy (25%) vs Low Heteroplasmy (9%)` <- averaged_metabo_wide$LLT2/averaged_metabo_wide$HLT2
sub_fc_df                  <- averaged_metabo_wide %>% 
                              select(c(Compound, `High Heteroplasmy (25%) vs WT`, `Low Heteroplasmy (9%) vs WT`, `High Heteroplasmy (25%) vs Low Heteroplasmy (9%)`)) %>% 
                              melt(id.vars = "Compound")
# calculate t.tests
sub_hlt2                   <- tpm %>% subset(Condition %in% c("HLT2", "CT2") )
sub_llt2                   <- tpm %>% subset(Condition %in% c("LLT2", "CT2") )
sub_hvsl                   <- tpm %>% subset(Condition %in% c("LLT2", "HLT2") )

results_hlt2               <- sub_hlt2 %>%
                              group_by(Compound) %>%
                              summarise(
                              t_test_HLTvsCT = (t.test(TPM ~ Condition)$p.value))

results_llt2               <- sub_llt2 %>%
                              group_by(Compound) %>%
                              summarise(
                              t_test_LLTvsCT = (t.test(TPM ~ Condition)$p.value))

results_hvl                <- sub_hvsl %>%
                              group_by(Compound) %>%
                              summarise(
                              t_test_LLTvsHHT = (t.test(TPM ~ Condition)$p.value))

results_hlt2$p.adj.hllt    <- p.adjust(results_hlt2$t_test_HLTvsCT, method = "BH")
results_llt2$p.adj.lllt    <- p.adjust(results_llt2$t_test_LLTvsCT, method = "BH")
results_hvl$p.adj.hvl      <- p.adjust(results_hvl$t_test_LLTvsHHT, method = "BH")

results_hvl_sign <- results_hvl[results_hvl$p.adj.hvl < 0.05,]

sub_fc_df                  <- sub_fc_df %>% 
                              left_join(results_hlt2, by = "Compound") %>% 
                              left_join(results_llt2, by = "Compound") %>% 
                              left_join(results_hvl, by = "Compound")

sub_fc_df                  <- sub_fc_df[order(log2(sub_fc_df$value), decreasing = TRUE), ]
sub_fc_df$Compound         <- factor(sub_fc_df$Compound , levels = unique(sub_fc_df$Compound))

write.csv(sub_fc_df, file = "~/Desktop/reznik/rrna-hotspots/data/processed/fig3_tables/metabolomics_foldchange.csv", row.names = F)
metabolomoics_heatmap <- ggplot(sub_fc_df, aes(x = factor(variable, levels = c("Low Heteroplasmy (9%) vs WT", "High Heteroplasmy (25%) vs WT")), y = Compound, fill = log2(value))) + 
  geom_tile(width = 0.8, linewidth = 0) + 
  scale_fill_gradient2(low = "#80b1d3", mid = "white", high = "#fb8072", midpoint = 0, name = "log2(FC)") + 
  theme_std() + 
  theme(axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank()) + 
  geom_text(aes(label = paste0(
                  case_when(
                    p.adj.hllt < 0.001 ~ "*",
                    p.adj.hllt < 0.01  ~ "*",
                    p.adj.hllt < 0.05  ~ "*",
                    TRUE ~ ""
                  ),
                  case_when(
                    p.adj.lllt < 0.001 ~ "*",
                    p.adj.lllt < 0.01  ~ "*",
                    p.adj.lllt < 0.05  ~ "*",
                    TRUE ~ ""
                  )
                )),
            color = "black", size = 5, vjust = 1) + 
  labs(x = "Heteroplasmy", y = "")

if(save){ggsave(metabolomoics_heatmap, file = paste0(results_dir, "/fig3/fig3_metabolomics_heatmap.pdf"), width = 3, height = 3) }
```
## Fig 3g BASAL OCR

For reference: 
ns: p > 0.05

*: p <= 0.05

**: p <= 0.01

***: p <= 0.001

****: p <= 0.0001
```{r}
ocr_long                 <- pivot_longer(ocr, cols = c("Low Heteroplasmy (24%)", "High Heteroplasmy (40%)", "WT"))
ocr_long$name            <- factor(ocr_long$name, levels = c("WT", "Low Heteroplasmy (24%)", "High Heteroplasmy (40%)"))

comparisons              <- list(c("WT", "High Heteroplasmy (40%)"), c("WT", "Low Heteroplasmy (24%)"))

ocr_boxplot              <- ggplot(ocr_long, aes(x = name, y = value, fill = name)) + 
                            geom_boxplot(outlier.shape = NA,
                                         width = 0.5) + 
                            geom_jitter(alpha = 0.8, width = 0.25, fill = "black", size = 1) + 
                            theme_std() + 
                            theme(legend.position = "none") + 
                            stat_compare_means(comparisons = comparisons, 
                            method = "t.test", 
                            p.adjust.methods = "BH", 
                            label = "p.signif", 
                            tip.length = 0,
                            step.increase = 0.05,
                            vjust = 0.5) + 
                            scale_x_discrete(expand = c(0.15,0)) + 
                            labs(x = "Heteroplasmy", y = "Basal OCR (norm.)") + 
                            scale_fill_manual(values = c("#d9d9d9", "#80b1d3", "#fb8072")) 

if(save){ggsave(ocr_boxplot, file = paste0(results_dir, "/fig3/fig3_ocr_boxplot.pdf"), width = 1.5, height = 3)}
```
# Fig 3i VOLCANO PLOT PROTEOMICS
```{r}
volcano_proteomics$p_values     <- 10^(-volcano_proteomics$logp1)
volcano_proteomics$p.adj        <- p.adjust(volcano_proteomics$p_values, method = "BH")
volcano_proteomics$p.adj.log    <- -log10(volcano_proteomics$p.adj)
volcano_proteomics$fc_type      <- ifelse(volcano_proteomics$p_values < 0.01 & volcano_proteomics$logFC1 > 0.5, "up",
                                          ifelse(volcano_proteomics$p_values < 0.01 & volcano_proteomics$logFC1 < -0.5, "down", "none"))

label_data                      <- volcano_proteomics %>% 
                                   subset(fc_type != "none")

proteomics_volcano_plot        <- ggplot(volcano_proteomics, aes(x = logFC1, y = logp1)) + 
                                   geom_point(alpha = 0.5, size = 1, aes(colour = fc_type)) + 
                                   theme_classic(base_size = 7, base_family = "ArialMT") + 
                                   geom_hline(yintercept = 2, linetype = "dashed", linewidth = 0.5) + 
                                   geom_vline(xintercept = c(-0.5, 0.5), linetype = "dashed", linewidth = 0.5) + 
                                   labs(y = "-log10(Adjusted P-value)", x = "log10(FC)") + 
                                   scale_colour_manual(values = c("#80b1d3", "#d9d9d9", "#fb8072")) + 
                                   geom_text_repel(data = label_data, aes(label = Name), size = 1) + 
                                   theme(legend.position = "none")
if(save){ggsave(proteomics_volcano_plot, file = paste0(results_dir, "/fig3/results3_proteomics.pdf"), width = 3, height = 3, useDingbats = FALSE)}
```
## Fig 3j GSEA PROTEOMICS
```{r}
gsea_long                <- pivot_longer(gsea_proteomics, cols = c("High Heteroplasmy (33%)", "Low Heteroplasmy (10%)"))
gsea_long                <- gsea_long[order(gsea_long$value, decreasing = T), ]
gsea_long$Pathway        <- factor(gsea_long$Pathway, levels = (unique(gsea_long$Pathway)))


gsea_plot_proteomics     <- ggplot(gsea_long, aes(x = Pathway, y = value, fill = factor(name, levels = c("High Heteroplasmy (33%)", "Low Heteroplasmy (10%)")))) + 
                            geom_bar(stat = "identity", position = position_dodge(), width = 0.5, ) + 
                            theme_std() + 
                            labs(x = "", y = "Enrichment Factor", fill = "") + 
                            scale_y_continuous(expand = c(0,0)) + 
                            scale_x_discrete(expand = c(0,0))  +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, vjust = 0, hjust = 1)) + 
                            scale_fill_manual(values = c("#80b1d3", "#fb8072"))

if(save){ggsave(gsea_plot_proteomics, file = paste0(results_dir, "/fig3/fig3_proteomicsgsea.pdf"), width = 2, height = 4)}
```

